version: '3'

###
### VOLUMES
###

volumes:
  exchangedb:
  cssdb:

###
### NETWORKS
###

networks:
  hznnet:
    driver: bridge

###
### SERVICES
###

services:
  ##
  ## agbot
  ##
  agbot:
    image: openhorizon/amd64_agbot:2.23.17
    container_name: agbot
    privileged: true
    networks:
      hznnet:
        aliases: 
          - oh-agbot-agbot1
    restart: always
    ports:
      - 3091:3091
    volumes:
      - /home/dcmartin/GIT/old-horizon/exchange/certs:/certs
      - /home/dcmartin/GIT/old-horizon/exchange/agbot/agbot.config:/etc/horizon/anax.json
      - /home/dcmartin/GIT/old-horizon/exchange/publickey.pem:/etc/horizon/trust/mtn-publicKey.pem
      - /home/dcmartin/GIT/old-horizon/exchange/cacerts.pem:/etc/horizon/trust/horizon.pem
      - cssdb:/var/wiotp-edge/persist
      - /home/dcmartin/GIT/old-horizon/exchange/agbot/policy:/etc/agbot/policy.d
      - /home/dcmartin/GIT/old-horizon/exchange/agbot/colonus:/var/horizon
    environment:
      - AGBOT_NAME=agbot1
      - CSS_URL=http://exchange.dcmartin.com:9443
      - EXCH_APP_HOST=http://exchange.dcmartin.com:3090/v1
      - EXCH_ROOTPW=ask4it
      - HZN_AGBOT_API=http://exchange.dcmartin.com:3091
      - HZN_DISABLE_IPTABLES_MANIPULATION=true
  ##
  ## exchange-api
  ##
  exchange-api:
    image:  openhorizon/amd64_exchange-api:1.106.0
    container_name: exchange-api
    ports:
      - 3090:8080
    networks:
      hznnet:
        aliases: 
          - oh-exchange-api
    volumes:
      - /home/dcmartin/GIT/old-horizon/exchange/exchange/exchange.json:/etc/horizon/exchange/config.json
  ##
  ## exchange-db
  ##
  exchange-db:
    image: postgres:9
    container_name: exchange-db
    restart: always
    volumes:
      - exchangedb:/var/lib/postgresql/data
    networks:
      hznnet:
        aliases:
          - oh-exchange-db
    environment:
      - POSTGRES_DB=exchange
      - POSTGRES_USER=admin
  ##
  ## css
  ##
  css-api:
    image: openhorizon/amd64_cloud-sync-service:1.0.12
    container_name: css-api
    restart: always
    ports:
      - 9443:9443
    networks:
      hznnet:
        aliases:
          - oh-css-api
    volumes:
      - /home/dcmartin/GIT/old-horizon/exchange/css:/etc/edge-sync-service
      - /home/dcmartin/GIT/old-horizon/exchange/certs:/certs
      - cssdb:/var/wiotp-edge/persist
    environment:
      - HZN_EXCHANGE_URL=http://exchange.dcmartin.com:3090/v1
      - HZN_EXCHANGE_CA_CERT=/certs/domain.crt
  ##
  ## css-db
  ##
  css-db:
    image: mongo:4.0.6
    container_name: css-db
    restart: always
    volumes:
      - cssdb:/var/wiotp-edge/persist
    ports:
      - 27017:27017
    networks:
      hznnet:
        aliases:
          - oh-css-db
